kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader-binding-beta
  namespace: beta
subjects:
  - kind: ServiceAccount
    name: {{.Values.service.account.name}}
    namespace: beta
roleRef:
  kind: ClusterRole
  name: pod-reader-beta
  namespace: beta
  apiGroup: rbac.authorization.k8s.io
