FROM node:8.16.0-alpine as build-stage

WORKDIR /usr/src/app
RUN mkdir /newman-support
RUN ls -l
#COPY ./newman-tests/* /newman-support

RUN echo WOWZERS
#RUN npm install newman-4.5.1.tgz
#RUN newman -v
