pipeline {
  agent any

  tools {nodejs "NodeJS_9"}
  stages {
    stage('Test') {
      steps {
      // nodejs(nodeJSInstallationName: 'NodeJS_9') {sh 'npm install'}
         sh 'newman-tests/node_modules/newman/bin/newman -v'
        // sh 'npm i --prefix ./ newman'
      }
    }
  }
}