pipeline {
  agent any

  tools {nodejs "NodeJS_9"}
  stages {
    stage('Test') {
      steps {
      // nodejs(nodeJSInstallationName: 'NodeJS_9') {sh 'npm install'}
       sh 'cd newman-tests && ls -l'
         sh '''
         cd newman-tests && tar -xvf node-v6.11.0-linux-x64.tar.gz'
         ln -s node-v6.10.3-linux-x64/bin/node /usr/bin/node'
         ln -s node-v6.10.3-linux-x64/bin/npm /usr/bin/npm
         '''
         sh 'npm -v'
         sh 'node -v'
      }
    }
  }
}