pipeline {
    agent none


  stages {
       agent {
          dockerfile {
            filename "newman-tests/Dockerfile"
          }
        }

    stage('Test') {
      steps {
           sh 'docker'
      }
    }
  }
}